from __future__ import annotations

from manifest_helpers import bullets, card, equation_slot, flow, image_slot, slide, table, text


BLUE = "0D6EAF"
TEAL = "0A7A6E"
AMBER = "D97706"
GREEN = "047857"
RED = "B91C1C"
NAVY = "1B2A4A"

THESIS_FIG = "thesis/figures"
REPORT_FIG = "reports/thesis/report_thesis_20260209/figures"


def _thesis_png(name: str) -> str:
    return f"{THESIS_FIG}/{name}"


def _report_png(name: str) -> str:
    return f"{REPORT_FIG}/{name}"


def get_manifest() -> dict:
    slides = [
        {
            "number": 1,
            "kind": "title",
            "title": "Rotary (Furuta) Inverted Pendulum",
            "subtitle": "Modelling and experimental comparison of linear and sliding-mode controllers",
            "tag": "M.Tech Thesis  ·  Experiment 2",
            "author_line": "Piyush Tiwari  |  M.Tech (Control & Automation)  |  IIT Kanpur",
            "date_line": "April 2026",
            "elements": [],
        },
        slide(
            2,
            "content",
            "Problem Framing, Contributions, and Roadmap",
            "This deck keeps the hardware reality, the modelling choices, and the controller mathematics on the same thread.",
            elements=[
                card(
                    0.45,
                    1.15,
                    3.0,
                    1.45,
                    title="Problem framing",
                    bullets_list=[
                        "Upright-only balancing on a real stepper-driven Furuta rig",
                        "Measured base angle, but actuation still happens through open-loop STEP/DIR",
                        "Goal: show what it takes to make this experimentally repeatable",
                    ],
                ),
                card(
                    3.55,
                    1.15,
                    3.05,
                    1.45,
                    title="Project contributions",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "Measured-stepper retrofit using an AS5600 on the motor axis",
                        "First-principles L-shaped rig model with acceleration-input control design",
                        "Three upright controllers on one hardware platform",
                    ],
                ),
                card(
                    6.72,
                    1.15,
                    2.78,
                    1.45,
                    title="Roadmap",
                    bullets_list=[
                        "Hardware and sensing",
                        "Model and filter design",
                        "Linear, hybrid SMC, full-state SMC",
                        "Pinned experimental comparison",
                    ],
                ),
                card(
                    0.45,
                    2.85,
                    9.05,
                    1.7,
                    title="Thesis stance",
                    stripe=TEAL,
                    bullets_list=[
                        "The analytic laws are derived cleanly, but each one is followed by the firmware protections required by the stepper platform.",
                        "Acceleration is treated as the abstract control input because that matches the actual firmware path: acceleration → commanded speed → stepper.",
                        "The comparison is rigorous but honest: it uses seven pinned runs H1–H3, N1, and T1–T3, so conclusions are qualitative and metric-based, not statistical.",
                    ],
                ),
            ],
        ),
        slide(
            3,
            "content",
            "Motivation and Problem Statement",
            "The project is interesting because the plant is classic, but the actuator and sensing stack are not.",
            elements=[
                card(
                    0.45,
                    1.18,
                    4.35,
                    2.0,
                    title="Why not just use a standard servo rig?",
                    bullets_list=[
                        "The base is driven by a NEMA17 stepper through FastAccelStepper, not by a torque-controlled servo.",
                        "Missed motion is possible under load, so commanded step count is not enough for feedback.",
                        "The work is therefore both a controls problem and a hardware-software integration problem.",
                    ],
                ),
                card(
                    5.0,
                    1.18,
                    4.5,
                    2.0,
                    title="Practical problem statement",
                    stripe=TEAL,
                    bullets_list=[
                        "Keep the pendulum upright near α = 0 while respecting ±80° base travel and ±30° pendulum safety limits.",
                        "Estimate the required states at 200 Hz from noisy absolute encoders on a multiplexed I²C bus.",
                        "Compare a linear controller, a pendulum-surface SMC, and a full-state surface SMC on the same rig.",
                    ],
                ),
                card(
                    0.45,
                    3.45,
                    4.35,
                    1.0,
                    title="Naive failure mode",
                    fill="FEF2F2",
                    stripe=RED,
                    body="If the controller asks for recovery torque that the stepper cannot realize, the measured state continues to look bad, and the controller can keep demanding more aggressive motion until the pendulum leaves the upright window.",
                ),
                card(
                    5.0,
                    3.45,
                    4.5,
                    1.0,
                    title="Thesis objective",
                    fill="ECFDF5",
                    stripe=GREEN,
                    body="Build a technically defensible pipeline from hardware retrofit to modelling to controller implementation and quantify what each controller actually does on the real platform.",
                ),
            ],
        ),
        slide(
            4,
            "content",
            "Why Is the Furuta Pendulum Hard?",
            "The instability is fast, the plant is underactuated, and this platform adds actuator mismatch on top of that.",
            elements=[
                equation_slot(
                    "s04_linear_open_loop",
                    r"\ddot{\alpha} = 100.8\,\alpha - 1.952\,\ddot{\theta}",
                    0.6,
                    1.2,
                    4.2,
                    0.6,
                    font_size=22,
                ),
                card(
                    5.05,
                    1.15,
                    1.4,
                    1.25,
                    title="Open-loop pole",
                    stripe=RED,
                    fill="FEF2F2",
                    body=r"$\lambda=\pm 12.47\ \mathrm{rad/s}$",
                ),
                card(
                    6.65,
                    1.15,
                    1.4,
                    1.25,
                    title="Base travel",
                    body=r"$|\theta| \le 80^\circ$",
                ),
                card(
                    8.25,
                    1.15,
                    1.25,
                    1.25,
                    title="Engage window",
                    body=r"$|\alpha|<3^\circ,\ |\dot{\alpha}|<20^\circ/s$",
                ),
                card(
                    0.45,
                    2.25,
                    4.45,
                    2.0,
                    title="Classical difficulty",
                    bullets_list=[
                        "Underactuated system: the pendulum is not actuated directly; only the base is.",
                        "The unstable mode is fast enough that estimation and actuation lag matter immediately.",
                        "Nonlinear gravity and centrifugal coupling remain active even near upright.",
                    ],
                ),
                card(
                    5.05,
                    2.25,
                    4.45,
                    2.0,
                    title="Platform-specific difficulty",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "The controller computes acceleration, but the firmware realizes it by integrating to a speed command.",
                        "The base is measured in closed loop, but the motor itself is still commanded open loop.",
                        "Sensor mux glitches, missed steps, and mechanical travel limits all feed back into control design.",
                    ],
                ),
            ],
        ),
        slide(
            5,
            "content",
            "Hardware Overview",
            "This is a custom stepper-driven rotary inverted pendulum with an L-shaped pendulum and dual absolute encoders.",
            elements=[
                image_slot("rig_photo", _thesis_png("rig_photo.png"), 0.45, 1.18, 4.9, 3.3, fit="contain"),
                text(0.55, 4.55, 4.75, 0.28, "Custom stepper-driven Furuta rig used for all experiments.", size=9, color="64748B", italic=True),
                card(
                    5.55,
                    1.18,
                    3.95,
                    1.55,
                    title="Main hardware stack",
                    bullets_list=[
                        "Arduino Mega 2560 + TMC2209 + FastAccelStepper",
                        "NEMA17 stepper at 1600 microsteps/rev",
                        "Two AS5600 absolute encoders via PCA9548A mux",
                    ],
                ),
                card(
                    5.55,
                    2.92,
                    3.95,
                    1.55,
                    title="Mechanical plant",
                    stripe=TEAL,
                    bullets_list=[
                        "Horizontal arm rotating about the vertical base axis θ",
                        "L-shaped pendulum with horizontal pivot shaft and vertical swinging segment α",
                        "Three 688RS bearings supporting the pendulum pivot",
                    ],
                ),
            ],
        ),
        slide(
            6,
            "key",
            "Sensor Architecture: Two AS5600s Through One I²C Mux",
            "The sensing path is simple in concept but critical in practice because both encoders share the same fixed AS5600 address.",
            key_contribution=True,
            elements=[
                flow(
                    0.55,
                    1.28,
                    8.9,
                    0.95,
                    [
                        {"label": "Pendulum\\nAS5600", "fill": "D6E8F5"},
                        {"label": "Base\\nAS5600", "fill": "D6E8F5"},
                        {"label": "PCA9548A\\nchannel select", "fill": "EEF5FB"},
                        {"label": "200 µs\\nsettle delay", "fill": "EEF5FB"},
                        {"label": "Arduino\\nWire @ 400 kHz", "fill": "D6E8F5"},
                    ],
                ),
                card(
                    0.55,
                    2.55,
                    4.25,
                    1.75,
                    title="Measurement details that matter",
                    bullets_list=[
                        "Channel 0 reads α, channel 1 reads θ.",
                        "Both sensors are 12-bit absolute encoders over [0, 360°).",
                        "The firmware averages 25 calibration samples to reduce roughly 0.5° single-sample noise.",
                    ],
                ),
                card(
                    5.05,
                    2.55,
                    4.4,
                    1.75,
                    title="Why this deserves emphasis",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "The mux is not cosmetic; it is the enabling mechanism that makes dual-AS5600 sensing possible on one bus.",
                        "Noise handling starts at the wiring and magnet geometry, not only in software.",
                        "Every later derivative and controller estimate depends on this sensing path being trustworthy.",
                    ],
                ),
            ],
        ),
        slide(
            7,
            "key",
            "Stepper Motor → Measured Axis: Closed-Loop Base Tracking Retrofit",
            "The stepper is still commanded open loop, but the output shaft is now directly measured by a coaxial AS5600 assembly.",
            key_contribution=True,
            elements=[
                image_slot("sensor_front", _thesis_png("sensor_housing_front.png"), 0.55, 1.2, 2.7, 1.55),
                image_slot("sensor_back", _thesis_png("sensor_housing_back.png"), 3.45, 1.2, 2.7, 1.55),
                image_slot("sensor_fixed", _thesis_png("sensor_housing_fixed_to_motor.png"), 6.35, 1.2, 2.7, 1.55),
                text(0.75, 2.8, 2.25, 0.2, "Front view", size=9, color="64748B", align="center", italic=True),
                text(3.65, 2.8, 2.25, 0.2, "Back view", size=9, color="64748B", align="center", italic=True),
                text(6.55, 2.8, 2.25, 0.2, "Mounted on the motor base", size=9, color="64748B", align="center", italic=True),
                card(
                    0.55,
                    3.2,
                    4.2,
                    1.45,
                    title="Physical trick",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "A magnet is fixed coaxially to the motor output shaft.",
                        "A rigid 3D-printed housing keeps the AS5600 aligned with controlled air gap.",
                        "This turns the motor axis into a measured state instead of trusting commanded steps.",
                    ],
                ),
                card(
                    5.05,
                    3.2,
                    4.3,
                    1.45,
                    title="Why it is not a true servo yet",
                    bullets_list=[
                        "The controller now knows the actual base angle θ.",
                        "But the TMC2209 still receives STEP/DIR speed commands, not torque commands.",
                        "So the measured axis is closed-loop in sensing, while actuation remains open-loop in realization.",
                    ],
                ),
            ],
        ),
        slide(
            8,
            "content",
            "Hardware Constraints and Limitations",
            "The controller design is shaped as much by hardware limits as by the equations.",
            elements=[
                card(0.55, 1.18, 2.15, 1.45, title="Mechanical travel", bullets_list=[r"Base hard limit: $|\theta|>80^\circ$", r"Soft outward clamp begins near $78^\circ$", r"Pendulum hard limit: $|\alpha|>30^\circ$"]),
                card(2.95, 1.18, 2.15, 1.45, title="Actuation mismatch", stripe=RED, fill="FEF2F2", bullets_list=["No torque control", "Acceleration integrated to commanded speed", "Motor can stall or miss motion"]),
                card(5.35, 1.18, 1.95, 1.45, title="Loop timing", bullets_list=[r"$T_s=5$ ms", "200 Hz control loop", "About 50 Hz logging"]),
                card(7.55, 1.18, 1.95, 1.45, title="Stall monitor", bullets_list=[r"Expect motion above 500 steps/s", r"Warn if $|\Delta\theta|<0.10^\circ$ for 150 ms"]),
                card(
                    0.55,
                    2.9,
                    4.45,
                    1.55,
                    title="What this means for controller design",
                    bullets_list=[
                        "The implemented law must be stepper-friendly: bounded speed, bounded acceleration, and robust to missed motion.",
                        "Any claim of stability must be read together with the firmware aborts, soft limits, and actuator shaping.",
                    ],
                ),
                card(
                    5.25,
                    2.9,
                    4.25,
                    1.55,
                    title="Firmware response to failure",
                    stripe=TEAL,
                    bullets_list=[
                        "Soft-limit suppression near the base stop",
                        "Predictable disarm to IDLE after debounced limit violation",
                        "Auto-rearm only after the pendulum re-enters the engage window",
                    ],
                ),
            ],
        ),
        slide(
            9,
            "content",
            "State Machine: Calibrate → Idle → Active",
            "The control software is organized around an explicit state machine instead of a monolithic loop with hidden assumptions.",
            elements=[
                flow(
                    0.75,
                    1.35,
                    8.6,
                    1.05,
                    [
                        {"label": "CALIBRATE", "fill": "D6E8F5"},
                        {"label": "IDLE", "fill": "EEF5FB"},
                        {"label": "ACTIVE", "fill": "ECFDF5"},
                    ],
                ),
                card(
                    0.65,
                    2.75,
                    4.2,
                    1.65,
                    title="Engage logic",
                    bullets_list=[
                        r"Require $|\alpha|<3^\circ$ and $|\dot{\alpha}|<20^\circ/s$",
                        "Hold the condition for 20 ticks = 100 ms before engage",
                        "Keep derivative history warm when transitioning from IDLE to ACTIVE",
                    ],
                ),
                card(
                    5.05,
                    2.75,
                    4.2,
                    1.65,
                    title="Disarm logic",
                    stripe=RED,
                    fill="FEF2F2",
                    bullets_list=[
                        "Debounced FALLEN detection over 3 ticks",
                        "Immediate nonlinear abort outside the upright-only SMC window",
                        "Disable stepper outputs and return to IDLE in a predictable way",
                    ],
                ),
            ],
        ),
        slide(
            10,
            "content",
            "Measurement Pipeline Before Any Controller Sees the States",
            "The estimator is intentionally simple, but the preprocessing around it is where most of the practical robustness comes from.",
            elements=[
                flow(
                    0.55,
                    1.28,
                    8.95,
                    0.95,
                    [
                        {"label": "Read raw\\nα, θ", "fill": "D6E8F5"},
                        {"label": "Wrap-safe\\nangle diff", "fill": "EEF5FB"},
                        {"label": "Reject >30°\\none-tick jumps", "fill": "FEF2F2"},
                        {"label": "Tustin\\nderivative filter", "fill": "D6E8F5"},
                        {"label": "Clamp\\nα̇, θ̇", "fill": "EEF5FB"},
                    ],
                ),
                card(
                    0.55,
                    2.55,
                    4.15,
                    1.85,
                    title="Key numerical settings",
                    bullets_list=[
                        r"Nominal loop: 200 Hz, logging: about 50 Hz",
                        r"Jump rejection threshold: $30^\circ$ per control tick",
                        r"Derivative clamps: $|\dot{\alpha}|, |\dot{\theta}| \le 300^\circ/s$",
                    ],
                ),
                card(
                    5.0,
                    2.55,
                    4.45,
                    1.85,
                    title="Why this stage is central",
                    stripe=TEAL,
                    bullets_list=[
                        "Both SMC surfaces depend directly on α̇, so bad derivative estimates immediately corrupt the control law.",
                        "The glitch handling forces impossible jumps to zero before the filter sees them.",
                        "This is why the estimator deserves a dedicated section rather than a one-line implementation note.",
                    ],
                ),
            ],
        ),
        slide(
            11,
            "content",
            "Modelling Strategy and Assumptions",
            "The model is idealized for control design, but the rig-specific geometry is retained instead of collapsing to the usual simplified pendulum picture.",
            elements=[
                card(
                    0.55,
                    1.2,
                    3.0,
                    2.05,
                    title="Assumptions",
                    bullets_list=[
                        "Rigid links and frictionless joints",
                        "No missed steps, no sensor glitches, no actuator saturation inside the analytic model",
                        "Commanded base acceleration θ̈ treated as the abstract input",
                    ],
                ),
                card(
                    3.75,
                    1.2,
                    2.75,
                    2.05,
                    title="Geometry retained",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "L-shaped pendulum instead of a single uniform rod",
                        "Mass split between non-swinging shaft mass and swinging mass",
                        "Pendulum COM computed from the real vertical rod plus tip mass",
                    ],
                ),
                card(
                    6.75,
                    1.2,
                    2.7,
                    2.05,
                    title="Grouped constants",
                    bullets_list=[
                        r"$K = m_p L_r l_p$",
                        r"$G = m_p g l_p$",
                        r"$\hat J_0 = \hat J_1 + m_p L_r^2$",
                    ],
                ),
                card(
                    0.55,
                    3.55,
                    8.9,
                    1.0,
                    title="Design choice to remember",
                    stripe=TEAL,
                    body="Torque appears in the full Euler–Lagrange equations, but the controller chapters intentionally rewrite the upright dynamics in acceleration-input form because that is the quantity the firmware can shape most directly.",
                ),
            ],
        ),
        slide(
            12,
            "content",
            "Kinematics and Coordinates",
            "The coupling between arm rotation and pendulum swing appears already at the position and velocity level.",
            elements=[
                card(
                    0.55,
                    1.25,
                    3.25,
                    1.9,
                    title="Coordinates",
                    bullets_list=[
                        r"$\theta$: base yaw angle",
                        r"$\alpha$: pendulum angle, with $\alpha=0$ upright",
                        r"$L_r$: motor axis to pendulum pivot",
                        r"$l_p$: pivot to pendulum COM",
                    ],
                ),
                equation_slot(
                    "s12_rp_v2",
                    r"\begin{aligned}\mathbf r_p &= L_r\mathbf e_r + l_p(\sin\alpha\,\mathbf e_t + \cos\alpha\,\mathbf k)\\[3pt]v^2 &= (L_r^2+l_p^2\sin^2\alpha)\dot\theta^2 + l_p^2\dot\alpha^2 + 2L_r l_p\cos\alpha\,\dot\theta\dot\alpha\end{aligned}",
                    4.0,
                    1.3,
                    5.1,
                    1.55,
                    font_size=20,
                ),
                card(
                    0.55,
                    3.45,
                    8.9,
                    1.15,
                    title="Interpretation",
                    stripe=TEAL,
                    body=r"The mixed term $2L_r l_p \cos\alpha\,\dot{\theta}\dot{\alpha}$ is the first clear sign that arm motion and pendulum motion are dynamically coupled even before the equations of motion are formed.",
                ),
            ],
        ),
        slide(
            13,
            "content",
            "Energies, Lagrangian, and Nonlinear Equations of Motion",
            "Once the rig-specific kinetic energy terms are retained, the Euler–Lagrange equations expose the exact nonlinear structure later used by the SMC designs.",
            elements=[
                equation_slot(
                    "s13_lagrangian",
                    r"\begin{aligned}T &= \tfrac12(\hat J_0+\hat J_2\sin^2\alpha)\dot\theta^2 + \tfrac12\hat J_2\dot\alpha^2 + K\cos\alpha\,\dot\theta\dot\alpha\\[3pt]V &= m_p g l_p \cos\alpha\\[3pt]\mathcal L &= T - V\end{aligned}",
                    0.65,
                    1.22,
                    4.25,
                    1.6,
                    font_size=18,
                ),
                equation_slot(
                    "s13_eom",
                    r"\begin{aligned}(\hat J_0+\hat J_2\sin^2\alpha)\ddot\theta + K\cos\alpha\,\ddot\alpha + \hat J_2\sin(2\alpha)\dot\theta\dot\alpha - K\sin\alpha\,\dot\alpha^2 &= \tau\\[4pt]K\cos\alpha\,\ddot\theta + \hat J_2\ddot\alpha - \tfrac12\hat J_2\sin(2\alpha)\dot\theta^2 - G\sin\alpha &= 0\end{aligned}",
                    5.1,
                    1.22,
                    4.15,
                    1.75,
                    font_size=16,
                ),
                card(
                    0.65,
                    3.35,
                    8.6,
                    1.2,
                    title="What matters later",
                    stripe=AMBER,
                    fill="FFFBEB",
                    body=r"These equations preserve the $\hat J_2\sin^2\alpha$ inertia modulation, the $\sin\alpha\cos\alpha\,\dot\theta^2$ centrifugal effect, and the coupling through $K\cos\alpha$, which are precisely the terms the nonlinear controllers exploit.",
                ),
            ],
        ),
        slide(
            14,
            "key",
            "What Our Model Retains vs Common Simplified Furuta Models",
            "The point is not rhetorical superiority; it is that several small-looking terms are exactly the ones that matter when you move from a teaching model to a custom stepper rig.",
            key_contribution=True,
            elements=[
                table(
                    0.55,
                    1.28,
                    8.95,
                    2.55,
                    headers=["Feature", "Common simplified model", "This thesis model"],
                    rows=[
                        ["Pendulum geometry", "Uniform rod abstraction", "Actual L-shaped geometry with shaft mass separated from swinging mass"],
                        ["Yaw inertia term", "Often constant", r"Retains $\hat J_2\sin^2\alpha$ inside the mass matrix"],
                        ["Pendulum rotational KE", "Often collapsed or omitted", r"Retains $T_{\mathrm{rot}}=\tfrac12J_p(\dot\alpha^2+\sin^2\alpha\,\dot\theta^2)$"],
                        ["Centrifugal coupling", "Often dropped near upright", r"Retains $\sin\alpha\cos\alpha\,\dot\theta^2$ explicitly"],
                        ["Control input used later", "Motor torque", "Commanded base acceleration matched to firmware architecture"],
                    ],
                    fill_header="FEF3C7",
                ),
                card(
                    0.55,
                    4.05,
                    8.95,
                    0.6,
                    title="Takeaway",
                    stripe=AMBER,
                    fill="FFFBEB",
                    body="The retained terms are not decorative complexity; they are the nonlinear structure that later appears again in the hybrid and full-state SMC derivations.",
                ),
            ],
        ),
        slide(
            15,
            "key",
            "Acceleration as Input: Why and How",
            "The decisive modelling move is to redesign the plant around the quantity the firmware can shape: commanded base acceleration.",
            key_contribution=True,
            elements=[
                equation_slot(
                    "s15_acc_input",
                    r"\ddot{\alpha} = A\sin\alpha + \sin\alpha\cos\alpha\,\dot{\theta}^2 - B\cos\alpha\,\ddot{\theta}",
                    0.75,
                    1.25,
                    4.45,
                    0.65,
                    font_size=22,
                ),
                flow(
                    5.45,
                    1.12,
                    3.85,
                    1.05,
                    [
                        {"label": "Controller\\ncomputes θ̈", "fill": "D6E8F5"},
                        {"label": "Integrate to\\ncommanded θ̇", "fill": "EEF5FB"},
                        {"label": "FastAccelStepper\\nspeed command", "fill": "D6E8F5"},
                    ],
                ),
                card(
                    0.55,
                    2.55,
                    4.4,
                    1.9,
                    title="Why this is architecturally cleaner",
                    bullets_list=[
                        "The control law becomes independent of the driver current-control internals.",
                        "The model matches the actual firmware path instead of pretending the stepper is torque controlled.",
                        "The downside is explicit: the hardware does not realize the commanded acceleration perfectly under load.",
                    ],
                ),
                card(
                    5.15,
                    2.55,
                    4.35,
                    1.9,
                    title="Numerical constants used later",
                    stripe=TEAL,
                    bullets_list=[
                        r"$A = 100.8$",
                        r"$B = 1.952$",
                        r"$k_s = 4.444\ \mathrm{step/deg}$",
                    ],
                ),
            ],
        ),
        slide(
            16,
            "content",
            "Linearisation About Upright",
            "Around α ≈ 0 the dynamics simplify enough for transparent state-space design while still keeping the main unstable physics visible.",
            elements=[
                equation_slot(
                    "s16_linearised",
                    r"\begin{aligned}\sin\alpha &\approx \alpha,\qquad \cos\alpha \approx 1\\[2pt]\ddot{\alpha} &= 100.8\,\alpha - 1.952\,\ddot{\theta}\end{aligned}",
                    0.75,
                    1.28,
                    4.35,
                    0.95,
                    font_size=20,
                ),
                card(
                    5.35,
                    1.2,
                    4.0,
                    1.05,
                    title="Open-loop fall rate",
                    stripe=RED,
                    fill="FEF2F2",
                    body=r"$\lambda = \pm \sqrt{G/J_{eq}} = \pm 12.47\ \mathrm{rad/s}$",
                ),
                card(
                    0.55,
                    2.65,
                    4.35,
                    1.85,
                    title="Why this linearisation is still useful",
                    bullets_list=[
                        "It exposes the unstable pendulum mode and the base-to-pendulum control effectiveness directly.",
                        "It gives a compact four-state plant for pole placement and LQR.",
                        "It is also the benchmark against which the nonlinear controllers are judged.",
                    ],
                ),
                card(
                    5.15,
                    2.65,
                    4.35,
                    1.85,
                    title="What it does not capture",
                    stripe=TEAL,
                    bullets_list=[
                        r"Nonlinear gravity $A\sin\alpha$ away from small angles",
                        r"Centrifugal coupling $\sin\alpha\cos\alpha\,\dot\theta^2$",
                        "Actuator saturation, missed steps, and sensing glitches",
                    ],
                ),
            ],
        ),
        slide(
            17,
            "content",
            "State-Space Representation",
            "The linear controller sees the rig as a four-state acceleration-input plant.",
            elements=[
                equation_slot(
                    "s17_state_space",
                    r"\begin{aligned}\mathbf x &= \begin{bmatrix}\theta & \alpha & \dot{\theta} & \dot{\alpha}\end{bmatrix}^{\mathsf T}\\[3pt]\dot{\mathbf x} &= \mathbf A \mathbf x + \mathbf B u,\qquad u\equiv \ddot{\theta}\\[3pt]\mathbf A &= \begin{bmatrix}0&0&1&0\\0&0&0&1\\0&0&0&0\\0&100.8&0&0\end{bmatrix},\qquad \mathbf B = \begin{bmatrix}0\\0\\1\\-1.952\end{bmatrix}\end{aligned}",
                    0.65,
                    1.28,
                    6.2,
                    1.35,
                    font_size=16,
                ),
                card(
                    7.05,
                    1.25,
                    2.35,
                    1.45,
                    title="Interpretation",
                    bullets_list=[
                        "θ̈ acts directly on θ̇",
                        "The same θ̈ also drives α̈ through −B",
                        "α feeds back as the unstable mode through A",
                    ],
                ),
                card(
                    0.65,
                    3.05,
                    8.75,
                    1.5,
                    title="Why this form is convenient",
                    stripe=TEAL,
                    body="It gives a direct bridge from the modelling chapter to controller synthesis: one can place poles analytically, derive an LQR gain, and then convert the result into stepper acceleration units using the fixed conversion $k_s=4.444$.",
                ),
            ],
        ),
        slide(
            18,
            "content",
            "Real Firmware Control Architecture",
            "This is the practical control-system block diagram actually implemented in the firmware, not an idealized textbook loop.",
            elements=[
                flow(
                    0.45,
                    1.25,
                    9.05,
                    1.1,
                    [
                        {"label": "AS5600\\nθ, α", "fill": "D6E8F5"},
                        {"label": "Mux select\\n+ settle", "fill": "EEF5FB"},
                        {"label": "Wrap +\\nglitch reject", "fill": "FEF2F2"},
                        {"label": "Tustin\\nfilter", "fill": "D6E8F5"},
                        {"label": "Controller", "fill": "FEF3C7"},
                        {"label": "Sign map", "fill": "EEF5FB"},
                        {"label": "θ̈ → θ̇\\nintegrator", "fill": "D6E8F5"},
                        {"label": "Deadband +\\nreverse stop + limits", "fill": "EEF5FB"},
                        {"label": "FastAccelStepper\\n→ motor", "fill": "D6E8F5"},
                    ],
                ),
                card(
                    0.55,
                    2.8,
                    4.35,
                    1.7,
                    title="Where the architecture differs from a servo textbook",
                    bullets_list=[
                        "The controller closes the loop around measured θ and α, but the actuator channel is still speed-command based.",
                        "The accel-to-speed integrator and speed deadband are part of the plant as seen by software.",
                        "This is why practical protections are not optional add-ons.",
                    ],
                ),
                card(
                    5.1,
                    2.8,
                    4.3,
                    1.7,
                    title="Explicit protection layers",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "Soft-limit suppression near ±80°",
                        "Stop-before-reverse to avoid direction chatter",
                        "Stall diagnostics based on measured θ, not only commanded speed",
                    ],
                ),
            ],
        ),
        slide(
            19,
            "key",
            "State Estimation: Bilinear Derivative Filter",
            "The derivative filter is mathematically small, but it is one of the highest leverage implementation choices in the whole project.",
            key_contribution=True,
            elements=[
                equation_slot(
                    "s19_filter",
                    r"\begin{aligned}H(s) &= \frac{s}{1+s/\omega_c}\\[3pt]y[n] &= b_0\,(x[n]-x[n-1]) - a_1\,y[n-1]\end{aligned}",
                    0.65,
                    1.25,
                    4.25,
                    0.95,
                    font_size=22,
                ),
                card(
                    5.15,
                    1.18,
                    4.2,
                    1.15,
                    title="Implemented coefficients",
                    stripe=TEAL,
                    body=r"$b_0 = \frac{2\omega_c}{2+\omega_c T_s},\qquad a_1 = \frac{\omega_c T_s - 2}{\omega_c T_s + 2}$",
                ),
                card(
                    0.55,
                    2.65,
                    4.25,
                    1.8,
                    title="Practical estimator details",
                    bullets_list=[
                        "Pendulum angle increments are wrapped into ±180° before filtering.",
                        "Rejected jumps force the corresponding increment to zero, so the filter does not see a false spike.",
                        "The filtered derivatives are then clamped before entering control.",
                    ],
                ),
                card(
                    5.05,
                    2.65,
                    4.35,
                    1.8,
                    title="Chosen operating point",
                    bullets_list=[
                        r"$\omega_c = 450\ \mathrm{rad/s}$, so $f_c \approx 71.6$ Hz",
                        r"$T_s = 5$ ms at 200 Hz",
                        r"Numerically: $b_0 = 211.7647,\ a_1 = 0.0588$",
                    ],
                ),
            ],
        ),
        slide(
            20,
            "content",
            "Filter Coefficient Derivation and Cutoff Selection",
            "The cutoff is high enough to keep derivative lag small, but the roll-off is still strong enough to tame encoder quantization and mux glitches.",
            elements=[
                equation_slot(
                    "s20_tustin",
                    r"\begin{aligned}s &\leftarrow \frac{2}{T}\frac{1-z^{-1}}{1+z^{-1}}\\[3pt]b_0 &= \frac{2\omega_c}{2+\omega_c T},\qquad a_1 = \frac{\omega_c T-2}{\omega_c T+2}\end{aligned}",
                    0.65,
                    1.25,
                    4.55,
                    0.9,
                    font_size=22,
                ),
                card(
                    5.45,
                    1.18,
                    3.95,
                    1.05,
                    title="Why not recompute every tick?",
                    body="The firmware measures actual dt for integrators and reference updates, but the derivative coefficients are fixed from the nominal 5 ms period to keep the implementation simple and stable.",
                ),
                card(
                    0.55,
                    2.65,
                    4.25,
                    1.85,
                    title="Cutoff tradeoff",
                    bullets_list=[
                        "Lower ωc: cleaner derivative, but more phase lag",
                        "Higher ωc: sharper derivative, but more noise amplification",
                        "Chosen value 450 rad/s was found to be a workable compromise on this hardware",
                    ],
                ),
                card(
                    5.05,
                    2.65,
                    4.35,
                    1.85,
                    title="Firmware-side safety around the filter",
                    stripe=TEAL,
                    bullets_list=[
                        "30° per-tick jump rejection before filtering",
                        "Derivative clamping after filtering",
                        "Diagnostic counters for glitch rejections and I²C faults",
                    ],
                ),
            ],
        ),
        slide(
            21,
            "content",
            "Linear Full-State Feedback by Pole Placement",
            "The baseline controller is derived analytically from the linearized acceleration-input plant.",
            elements=[
                equation_slot(
                    "s21_lin_feedback",
                    r"\begin{aligned}u &= -\mathbf K \mathbf x\\[3pt]\mathbf K &= \begin{bmatrix}k_\theta & k_\alpha & k_{\dot\theta} & k_{\dot\alpha}\end{bmatrix}\\[4pt]s^4 + a_3 s^3 + a_2 s^2 + a_1 s + a_0 &= 0\end{aligned}",
                    0.65,
                    1.22,
                    4.4,
                    1.05,
                    font_size=20,
                ),
                card(
                    5.3,
                    1.18,
                    4.1,
                    1.1,
                    title="Coefficient relations",
                    body=r"$a_3 = k_{\dot\theta} - B k_{\dot\alpha},\ a_2 = k_\theta - A - Bk_\alpha,\ a_1 = -A k_{\dot\theta},\ a_0 = -A k_\theta$",
                ),
                card(
                    0.55,
                    2.7,
                    4.35,
                    1.8,
                    title="Design idea",
                    bullets_list=[
                        "Choose a fast second-order factor for the pendulum mode.",
                        "Choose a slower second-order factor for the base-centering mode.",
                        "Match coefficients directly instead of using Ackermann’s formula or a numerical black box.",
                    ],
                ),
                card(
                    5.1,
                    2.7,
                    4.3,
                    1.8,
                    title="Why this baseline matters",
                    stripe=TEAL,
                    bullets_list=[
                        "The linear controller is the calmest and most interpretable controller in the thesis.",
                        "It also provides the shared base-centering gains reused later by the hybrid and full-state SMC implementations.",
                    ],
                ),
            ],
        ),
        slide(
            22,
            "content",
            "Closed-Form Gain Calculation and Stepper Conversion",
            "The gains are first derived in degree-space dynamics and then converted into stepper acceleration units.",
            elements=[
                equation_slot(
                    "s22_gain_formulas",
                    r"\begin{aligned}k_\theta &= -\frac{\tilde a_0}{A},\qquad k_{\dot\theta} = -\frac{\tilde a_1}{A}\\[3pt]k_{\dot\alpha} &= \frac{k_{\dot\theta}-\tilde a_3}{B},\qquad k_\alpha = \frac{k_\theta - A - \tilde a_2}{B}\end{aligned}",
                    0.65,
                    1.22,
                    4.55,
                    0.95,
                    font_size=21,
                ),
                card(
                    5.4,
                    1.15,
                    4.0,
                    1.25,
                    title="Firmware gains used in experiments",
                    stripe=GREEN,
                    fill="ECFDF5",
                    body=r"$K_\theta=31.5,\ K_\alpha=725.6,\ K_{\dot\theta}=28.3,\ K_{\dot\alpha}=73.5$",
                ),
                card(
                    0.55,
                    2.7,
                    4.1,
                    1.8,
                    title="Unit conversion",
                    bullets_list=[
                        r"$k_s = 1600/360 = 4.444\ \mathrm{step/deg}$",
                        "Theoretical gains are multiplied by ks to obtain stepper acceleration units.",
                        "The deployed gains are then tuned on hardware while preserving the analytic structure.",
                    ],
                ),
                card(
                    4.95,
                    2.7,
                    4.45,
                    1.8,
                    title="Why this slide matters",
                    stripe=TEAL,
                    bullets_list=[
                        "It shows the bridge from derivation to firmware constants explicitly.",
                        "The gains shown in code are not arbitrary empirical numbers; they sit on top of a closed-form design path.",
                    ],
                ),
            ],
        ),
        slide(
            23,
            "content",
            "LQR as a Secondary Design Path",
            "LQR is included as a compact alternative derivation, but the thesis keeps pole placement as the main transparent design route.",
            elements=[
                equation_slot(
                    "s23_lqr",
                    r"\min_u \int_0^\infty (\mathbf x^\mathsf T Q \mathbf x + u^\mathsf T R u)\,dt,\qquad \mathbf K_{\mathrm{LQR}} = R^{-1} B^\mathsf T P",
                    0.75,
                    1.28,
                    4.8,
                    0.6,
                    font_size=22,
                ),
                card(
                    5.8,
                    1.18,
                    3.55,
                    1.2,
                    title="Why it is not the main story",
                    bullets_list=[
                        "The resulting gain depends on chosen Q/R weights rather than explicit modal targets.",
                        "Pole placement was better for explaining the intended pendulum/base mode separation.",
                    ],
                ),
                card(
                    0.55,
                    2.75,
                    4.2,
                    1.65,
                    title="Why still include it",
                    bullets_list=[
                        "It confirms the same linearized plant can be handled with standard optimal control machinery.",
                        "It is useful as a cross-check and as a future tuning path if the cost function is made actuator-aware.",
                    ],
                ),
                card(
                    5.05,
                    2.75,
                    4.35,
                    1.65,
                    title="Design takeaway",
                    stripe=TEAL,
                    body="This thesis uses LQR as supporting evidence that the linearized model is internally consistent, not as a competing headline controller branch.",
                ),
            ],
        ),
        slide(
            24,
            "content",
            "Trapezoidal Reference Profiler and Stability Gates",
            "The nudge mode is not a separate controller; it is a reference-generation layer wrapped around the same balancing stack.",
            elements=[
                flow(
                    0.55,
                    1.25,
                    8.95,
                    0.95,
                    [
                        {"label": "User target\\nθ_target", "fill": "D6E8F5"},
                        {"label": "Trapezoidal\\nprofile", "fill": "EEF5FB"},
                        {"label": "Stability\\ngate", "fill": "FEF3C7"},
                        {"label": "Pause /\\nresume", "fill": "EEF5FB"},
                        {"label": "θ_ref, θ̇_ref, θ̈_ref", "fill": "D6E8F5"},
                    ],
                ),
                card(
                    0.55,
                    2.55,
                    4.15,
                    1.85,
                    title="Profile settings used in the thesis",
                    bullets_list=[
                        r"Target limit: $|\theta_{\mathrm{target}}| \le 35^\circ$",
                        r"Max reference speed: $12^\circ/s$",
                        r"Max reference acceleration: $60^\circ/s^2$",
                    ],
                ),
                card(
                    5.0,
                    2.55,
                    4.45,
                    1.85,
                    title="Pause / resume logic",
                    stripe=TEAL,
                    bullets_list=[
                        r"Keep moving only if $|\alpha|<5^\circ$ and $|\dot{\alpha}|<80^\circ/s$ after a 200 ms grace period",
                        "Debounce both stable and unstable conditions for 10 ticks",
                        "On instability, hand θref once to the current measured θ and hold there until the rig is calm again",
                    ],
                ),
            ],
        ),
        slide(
            25,
            "content",
            "Implementation Tricks in Firmware",
            "This slide collects the small choices that stop the real hardware from behaving like the ideal equations would suggest.",
            elements=[
                card(0.55, 1.18, 2.85, 1.4, title="Wrap + glitch handling", bullets_list=["Wrap-safe angle differences", "Reject >30° one-tick jumps", "Keep false spikes out of α̇ and θ̇"]),
                card(3.55, 1.18, 2.85, 1.4, title="Bias killers", stripe=TEAL, bullets_list=["Velocity leak in linear mode only", "Auto-trim the α reference slowly", "Clamp trim to ±1.5°"]),
                card(6.55, 1.18, 2.85, 1.4, title="Motor command shaping", bullets_list=["100 ms engage ramp", "Low-speed stop deadband", "Stop-before-reverse"]),
                card(0.55, 2.95, 2.85, 1.4, title="Watchdogs", stripe=RED, fill="FEF2F2", bullets_list=["Base stall detection from measured θ", "Limit debounce before FALLEN", "SMC upright-only abort window"]),
                card(3.55, 2.95, 2.85, 1.4, title="Tuning helpers", bullets_list=["Sign wizard for motor / θ / α / control direction", "EEPROM persistence for settings", "Runtime controller parameter commands"]),
                card(6.55, 2.95, 2.85, 1.4, title="Why these matter", stripe=AMBER, fill="FFFBEB", body="These are the difference between a controller law that looks correct on paper and a balancing session that survives repeated real-world trials."),
            ],
        ),
        slide(
            26,
            "content",
            "Linear Controller Performance",
            "The linear controller is the cleanest performer on this rig: calm in hold mode and capable of commanded base motion without a fall.",
            elements=[
                image_slot("hold_lin_timeseries", _report_png("hold_LIN_rep_session_20260209_095631_trial0_timeseries.png"), 0.55, 1.18, 4.35, 2.0, fit="contain"),
                image_slot("nudge_lin", _report_png("nudge_LIN_rep_session_20260209_114605_trial0_nudge.png"), 5.05, 1.18, 4.35, 2.0, fit="contain"),
                text(1.2, 3.2, 3.1, 0.22, "Hold run H1", size=9, color="64748B", align="center", italic=True),
                text(5.75, 3.2, 3.0, 0.22, "Nudge run N1", size=9, color="64748B", align="center", italic=True),
                card(
                    0.55,
                    3.55,
                    8.85,
                    1.0,
                    title="Readout",
                    stripe=GREEN,
                    fill="ECFDF5",
                    body="In the pinned dataset the linear controller gives the lowest hold-mode α RMS (0.513°), survives the tap run T1, and demonstrates commanded base-position moves while keeping the pendulum upright during N1.",
                ),
            ],
        ),
        slide(
            27,
            "key",
            "Hybrid SMC: Motivation and Sliding Surface",
            "The first nonlinear design keeps the sliding surface pendulum-centric and treats base centering as a second objective.",
            key_contribution=True,
            elements=[
                equation_slot(
                    "s27_smc_surface",
                    r"s = \dot{\alpha} + \lambda \alpha",
                    0.85,
                    1.28,
                    3.2,
                    0.55,
                    font_size=24,
                ),
                card(
                    4.35,
                    1.18,
                    5.0,
                    1.2,
                    title="Interpretation",
                    body=r"On the surface $s=0$, the pendulum follows $\dot{\alpha}=-\lambda\alpha$, so $\alpha(t)=\alpha_0 e^{-\lambda t}$ and $\lambda$ directly sets the desired decay rate.",
                ),
                card(
                    0.55,
                    2.75,
                    4.1,
                    1.7,
                    title="Why move to nonlinear control",
                    bullets_list=[
                        r"The linear controller ignores the exact $A\sin\alpha$ gravity term and the centrifugal coupling.",
                        "The SMC law uses the reduced nonlinear upright model directly.",
                        "This is especially attractive for moderate excursions where the small-angle approximation is visibly coarse.",
                    ],
                ),
                card(
                    4.95,
                    2.75,
                    4.45,
                    1.7,
                    title="Hybrid idea",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "The sliding surface handles pendulum stabilization only.",
                        "A separate gated PD-like base-centering term is later blended in.",
                        "This separation keeps tuning intuitive on the real rig.",
                    ],
                ),
            ],
        ),
        slide(
            28,
            "content",
            "Hybrid SMC: Control Law Derivation",
            "Start from the nonlinear acceleration-input plant, differentiate the sliding surface, and solve for the base acceleration that enforces the reaching law.",
            elements=[
                equation_slot(
                    "s28_smc_law",
                    r"\begin{aligned}f(\alpha,\dot{\alpha},\dot{\theta}) &= A\sin\alpha + \sin\alpha\cos\alpha\,\dot{\theta}^2 + \lambda\dot{\alpha}\\[4pt]\ddot{\theta} &= \frac{f(\alpha,\dot{\alpha},\dot{\theta}) + K\,\mathrm{sat}(s/\phi)}{B\cos\alpha}\end{aligned}",
                    0.65,
                    1.18,
                    4.8,
                    1.2,
                    font_size=18,
                ),
                card(
                    5.65,
                    1.18,
                    3.75,
                    1.2,
                    title="Experimental parameters",
                    body=r"$\lambda = 15,\ K = 800,\ \phi = 50,\ \gamma = 1.0$",
                ),
                card(
                    0.55,
                    2.75,
                    4.35,
                    1.7,
                    title="Numerical implementation notes",
                    bullets_list=[
                        "Angles are measured in degrees, but the nonlinear trigonometric terms are evaluated in radians.",
                        "A cosine floor protects the denominator: cos_safe = sign(cos α) max(|cos α|, 0.2).",
                        "The resulting θ̈ command is converted into stepper acceleration units and saturated.",
                    ],
                ),
                card(
                    5.1,
                    2.75,
                    4.3,
                    1.7,
                    title="Why the law is attractive",
                    stripe=TEAL,
                    bullets_list=[
                        "Explicit compensation of gravity and centrifugal drift",
                        "Direct design knobs: λ for decay, K for reaching, ϕ for boundary layer width",
                        "Still simple enough to run comfortably at 200 Hz on the Arduino Mega",
                    ],
                ),
            ],
        ),
        slide(
            29,
            "content",
            "Lyapunov Stability Proof for the Hybrid SMC Reaching Law",
            "The analytic law gives a clean reaching proof, but the firmware protections must be stated alongside it.",
            elements=[
                equation_slot(
                    "s29_lyapunov",
                    r"\begin{aligned}V(s) &= \tfrac12 s^2\\[2pt]\dot{V} &= s\dot{s} = -K\,s\,\mathrm{sat}(s/\phi)\le 0\\[2pt]|s|>\phi &\Rightarrow \dot{V}=-K|s|\end{aligned}",
                    0.75,
                    1.22,
                    4.0,
                    1.1,
                    font_size=21,
                ),
                card(
                    5.0,
                    1.18,
                    4.35,
                    1.2,
                    title="Finite-time reaching outside the boundary layer",
                    stripe=GREEN,
                    fill="ECFDF5",
                    body=r"The standard ideal reaching result is recovered: the surface is reached in finite time with a rate set by $K$ when $|s|>\phi$.",
                ),
                card(
                    0.55,
                    2.75,
                    4.25,
                    1.75,
                    title="Theory vs firmware",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "The proof applies to the analytic law before saturation, deadband, engage ramp, and abort logic are added.",
                        "The deployed firmware also enforces the upright-only validity window, cosine protection, and acceleration limits.",
                        "So the Lyapunov result is a design guide, not an unconditional hardware theorem.",
                    ],
                ),
                card(
                    5.05,
                    2.75,
                    4.3,
                    1.75,
                    title="Why keep the proof in the deck",
                    bullets_list=[
                        "It explains the logic of the controller rather than presenting SMC as a tuning heuristic.",
                        "It also shows exactly where the practical implementation begins to diverge from the ideal law.",
                    ],
                ),
            ],
        ),
        slide(
            30,
            "content",
            "Boundary Layer and Chattering Elimination",
            "The saturation function keeps the reaching law usable on the real stepper platform by softening the switching near the surface.",
            elements=[
                equation_slot(
                    "s30_sat",
                    r"\mathrm{sat}(x)=\begin{cases}+1,&x>1\\x,&|x|\le 1\\-1,&x<-1\end{cases},\qquad \dot{s}=-K\,\mathrm{sat}(s/\phi)",
                    0.75,
                    1.28,
                    4.55,
                    0.7,
                    font_size=21,
                ),
                card(
                    5.55,
                    1.18,
                    3.8,
                    1.05,
                    title="Chosen boundary layer",
                    body=r"$\phi = 50\ \mathrm{deg/s}$ in the pinned dataset",
                ),
                card(
                    0.55,
                    2.65,
                    4.2,
                    1.85,
                    title="Outside the layer",
                    bullets_list=[
                        "The reaching term behaves like sign(s), so the controller pulls aggressively toward the surface.",
                        "This is the part that provides the classical finite-time reaching behavior.",
                    ],
                ),
                card(
                    5.0,
                    2.65,
                    4.35,
                    1.85,
                    title="Inside the layer",
                    stripe=TEAL,
                    bullets_list=[
                        "The law becomes locally linear and smooths the control action.",
                        "This reduces chatter in commanded acceleration and therefore reduces harsh stepper commands near upright.",
                    ],
                ),
            ],
        ),
        slide(
            31,
            "content",
            "Hybrid SMC: Base-Centering Blend",
            "The controller is called hybrid because the pendulum-surface SMC is blended with a separate gated base-centering term.",
            elements=[
                equation_slot(
                    "s31_base_blend",
                    r"\ddot{\theta}_{\mathrm{base}} = \ddot{\theta}_{\mathrm{ref}} + K_{\theta}\theta_{\mathrm{err}} + K_{\dot{\theta}}\dot{\theta}_{\mathrm{err}},\qquad u_{\mathrm{cmd}}=u_{\mathrm{smc}}+\gamma u_{\mathrm{base}}",
                    0.65,
                    1.22,
                    5.0,
                    0.85,
                    font_size=18,
                ),
                card(
                    5.9,
                    1.18,
                    3.5,
                    1.1,
                    title="Gate used in firmware",
                    body=r"Enable only after 200 ms and only if $|\alpha|<5^\circ$ and $|\dot{\alpha}|<150^\circ/s$",
                ),
                card(
                    0.55,
                    2.7,
                    4.25,
                    1.8,
                    title="Why the blend is needed",
                    bullets_list=[
                        "A pendulum-only surface does not directly regulate the base position.",
                        "Small biases can make the arm random-walk even while the pendulum stays near upright.",
                        "The extra centering term is therefore a pragmatic fix for drift on the real rig.",
                    ],
                ),
                card(
                    5.0,
                    2.7,
                    4.4,
                    1.8,
                    title="What is special here",
                    stripe=AMBER,
                    fill="FFFBEB",
                    body="The two control objectives are intentionally decoupled: the SMC law dominates pendulum recovery, while the base-centering action is only allowed to act when the pendulum is already calm enough that the two objectives will not fight each other.",
                ),
            ],
        ),
        slide(
            32,
            "content",
            "Hybrid SMC Performance",
            "The hybrid SMC suppresses peak excursions well in the pinned hold run, but the tap run shows the practical limit of aggressive recovery on this stepper platform.",
            elements=[
                image_slot("hold_smc_timeseries", _report_png("hold_SMC_rep_session_20260209_095908_trial0_timeseries.png"), 0.55, 1.18, 4.35, 2.0, fit="contain"),
                image_slot("tap_smc_timeseries", _report_png("tap_SMC_rep_session_20260209_114953_trial0_timeseries.png"), 5.05, 1.18, 4.35, 2.0, fit="contain"),
                text(1.35, 3.2, 2.8, 0.22, "Hold run H2", size=9, color="64748B", align="center", italic=True),
                text(5.85, 3.2, 2.8, 0.22, "Tap run T2", size=9, color="64748B", align="center", italic=True),
                card(
                    0.55,
                    3.55,
                    8.85,
                    1.0,
                    title="Readout",
                    stripe=AMBER,
                    fill="FFFBEB",
                    body="In the pinned hold run the hybrid SMC gives the smallest max |α| and max |θ|. In the pinned tap run it eventually falls, which is consistent with the platform-level limitation that the controller can demand recovery harder than the open-loop stepper can realize.",
                ),
            ],
        ),
        slide(
            33,
            "key",
            "Full-State SMC: Unified Sliding Surface",
            "The third controller encodes pendulum and base objectives in one scalar sliding manifold instead of separating them.",
            key_contribution=True,
            elements=[
                equation_slot(
                    "s33_smc4_surface",
                    r"s = \dot{\alpha} + \lambda_{\alpha}\alpha + k\bigl(\dot{\theta}_{\mathrm{err}} + \lambda_{\theta}\theta_{\mathrm{err}}\bigr)",
                    0.75,
                    1.28,
                    5.4,
                    0.65,
                    font_size=20,
                ),
                card(
                    6.4,
                    1.18,
                    3.0,
                    1.15,
                    title="Pinned parameters",
                    body=r"$\lambda_{\alpha}=15,\ \lambda_{\theta}=2,\ k=0.5,\ K=800,\ \phi=50$",
                ),
                card(
                    0.55,
                    2.7,
                    4.25,
                    1.8,
                    title="Interpretation of the new terms",
                    bullets_list=[
                        r"$\lambda_{\alpha}$ shapes pendulum decay on the surface",
                        r"$\lambda_{\theta}$ shapes base error decay",
                        r"$k$ couples base tracking into the sliding condition",
                    ],
                ),
                card(
                    5.0,
                    2.7,
                    4.4,
                    1.8,
                    title="What is special here",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "Pendulum stabilization and base tracking are no longer separate objectives blended later.",
                        "The denominator of the control law now depends directly on k, which makes safety analysis much more important.",
                    ],
                ),
            ],
        ),
        slide(
            34,
            "key",
            "Denominator Safety and Singularity Management in Full-State SMC",
            "This controller is mathematically elegant, but it introduces a denominator that can become dangerously small if the coupling is not managed.",
            key_contribution=True,
            elements=[
                equation_slot(
                    "s34_smc4_den",
                    r"\dot{s} = f_0(\alpha,\dot{\theta}) + \lambda_{\alpha}\dot{\alpha} + k\lambda_{\theta}\dot{\theta}_{\mathrm{err}} - k\ddot{\theta}_{\mathrm{ref}} + (k - B\cos\alpha)\ddot{\theta}",
                    0.65,
                    1.22,
                    5.3,
                    0.85,
                    font_size=17,
                ),
                equation_slot(
                    "s34_den_condition",
                    r"\ddot{\theta} = \frac{\cdots}{B\cos\alpha - k},\qquad |B\cos\alpha_{\mathrm{safe}} - k_{\mathrm{Eff}}| \ge 0.60",
                    0.75,
                    2.18,
                    5.1,
                    0.6,
                    font_size=20,
                ),
                card(
                    6.15,
                    1.18,
                    3.25,
                    1.55,
                    title="Implemented safeguards",
                    bullets_list=[
                        r"Cosine floor: $|\cos\alpha| \ge 0.2$ with sign preserved",
                        r"Coupling limit: $k \le 1.20$",
                        "Coupling ramp-in over 200 ms after engage",
                    ],
                ),
                card(
                    6.15,
                    2.95,
                    3.25,
                    1.55,
                    title="Theory vs firmware",
                    stripe=AMBER,
                    fill="FFFBEB",
                    bullets_list=[
                        "The analytic law assumes denominator regularity.",
                        "The firmware explicitly enforces that regularity by modifying k_eff and the denominator margin online.",
                        "This is one of the clearest places where implementation-aware control design matters.",
                    ],
                ),
            ],
        ),
        slide(
            35,
            "content",
            "Full-State SMC: Control Law and Implementation Safeguards",
            "The full law is nonlinear, coupled, and explicitly actuator-shaped for the stepper platform.",
            elements=[
                equation_slot(
                    "s35_smc4_law",
                    r"\ddot{\theta} = \frac{f_0(\alpha,\dot{\theta}) + \lambda_{\alpha}\dot{\alpha} + k_{\mathrm{Eff}}\lambda_{\theta}\dot{\theta}_{\mathrm{err}} - k_{\mathrm{Eff}}\ddot{\theta}_{\mathrm{ref}} + K\,\mathrm{sat}(s/\phi)}{B\cos\alpha_{\mathrm{safe}} - k_{\mathrm{Eff}}}",
                    0.65,
                    1.18,
                    5.2,
                    0.95,
                    font_size=16,
                ),
                card(
                    6.1,
                    1.18,
                    3.3,
                    1.05,
                    title="SMC4-specific caps",
                    body=r"$u_{\max}=12000\ \mathrm{steps/s^2},\ \dot{\theta}_{\max}=2000\ \mathrm{steps/s}$",
                ),
                card(
                    0.55,
                    2.65,
                    4.2,
                    1.85,
                    title="Additional clamps in firmware",
                    bullets_list=[
                        r"Clamp $|\theta_{\mathrm{err}}| \le 78^\circ$",
                        r"Clamp $|\dot{\theta}_{\mathrm{err}}| \le 200^\circ/s$",
                        r"Clamp internal $|\dot{\alpha}| \le 200^\circ/s$ in the SMC4 math",
                    ],
                ),
                card(
                    5.0,
                    2.65,
                    4.4,
                    1.85,
                    title="Practical reading of this controller",
                    stripe=TEAL,
                    bullets_list=[
                        "It is the most unified controller mathematically.",
                        "It is also the most sensitive to actuator limits and denominator conditioning on this platform.",
                        "That is why the implementation includes more shaping and more guards than the hybrid SMC.",
                    ],
                ),
            ],
        ),
        slide(
            36,
            "content",
            "Full-State SMC Performance",
            "The full-state surface controller balances upright in calm conditions, but the required protection logic is visible in both its diagnostics and its effort levels.",
            elements=[
                image_slot("hold_smc4_timeseries", _report_png("hold_SMC4_rep_session_20260209_121635_trial0_timeseries.png"), 0.55, 1.18, 4.2, 1.85, fit="contain"),
                image_slot("hold_smc4_den", _report_png("hold_SMC4_rep_session_20260209_121635_trial0_sparse_den.png"), 4.95, 1.18, 2.15, 1.85, fit="contain"),
                image_slot("hold_smc4_keff", _report_png("hold_SMC4_rep_session_20260209_121635_trial0_sparse_kEff.png"), 7.3, 1.18, 2.1, 1.85, fit="contain"),
                text(1.35, 3.08, 2.5, 0.22, "Hold run H3", size=9, color="64748B", align="center", italic=True),
                text(5.25, 3.08, 1.55, 0.22, "Protected denominator", size=9, color="64748B", align="center", italic=True),
                text(7.45, 3.08, 1.75, 0.22, "Effective coupling", size=9, color="64748B", align="center", italic=True),
                card(
                    0.55,
                    3.45,
                    8.85,
                    1.1,
                    title="Readout",
                    stripe=AMBER,
                    fill="FFFBEB",
                    body="In the pinned hold run the controller stays upright, but it uses much higher effort than the linear and hybrid controllers. In the pinned tap run T3 it falls, reinforcing that this controller is the most sensitive to actuator limits and safety shaping on the present hardware.",
                ),
            ],
        ),
        slide(
            37,
            "content",
            "Three-Controller Comparison",
            "This comparison is rigorous in sourcing but intentionally modest in claim strength: it is based on one pinned run per condition.",
            elements=[
                table(
                    0.55,
                    1.12,
                    8.95,
                    1.45,
                    headers=["Controller", "Hold α RMS", "Hold acc RMS", "Tap outcome", "Tap acc RMS"],
                    rows=[
                        ["Linear", "0.513°", "1354.846", "Success (T1)", "1695.658"],
                        ["Hybrid SMC", "0.826°", "1465.582", "Fallen (T2)", "1493.067"],
                        ["Full-state SMC", "1.61°", "3364.957", "Fallen (T3)", "3843.042"],
                    ],
                    fill_header="D6E8F5",
                ),
                image_slot("hold_metric_bars", _report_png("hold_metric_bars.png"), 0.55, 2.78, 4.25, 1.45, fit="contain"),
                image_slot("tap_metric_bars", _report_png("tap_metric_bars.png"), 5.05, 2.78, 4.25, 1.45, fit="contain"),
                text(1.6, 4.22, 2.1, 0.2, "Pinned hold metrics", size=9, color="64748B", align="center", italic=True),
                text(6.1, 4.22, 2.1, 0.2, "Pinned tap metrics", size=9, color="64748B", align="center", italic=True),
                card(
                    0.55,
                    4.45,
                    8.85,
                    0.45,
                    title="Dataset caveat",
                    stripe=AMBER,
                    fill="FFFBEB",
                    body="Provenance: H1–H3, N1, and T1–T3 only. The deck therefore reports a qualitative, metric-based comparison rather than a statistical controller ranking.",
                ),
            ],
        ),
        slide(
            38,
            "conclusion",
            "Contributions, Limitations, and Next Steps",
            "The final message is that the thesis contributes both a model/controller stack and a practical recipe for making a custom stepper Furuta rig experimentally usable.",
            elements=[
                card(
                    0.45,
                    1.15,
                    3.0,
                    2.45,
                    title="Main contributions",
                    stripe=AMBER,
                    fill="1B2A4A",
                    title_color="FFFFFF",
                    body_color="F6F8FA",
                    bullets_list=[
                        "Measured-stepper retrofit with dual AS5600 sensing",
                        "L-shaped first-principles model with acceleration-input control framing",
                        "Three controller implementations on one platform",
                    ],
                ),
                card(
                    3.65,
                    1.15,
                    2.85,
                    2.45,
                    title="Key limitations",
                    stripe=RED,
                    fill="1B2A4A",
                    title_color="FFFFFF",
                    body_color="F6F8FA",
                    bullets_list=[
                        "One pinned run per condition only",
                        "No explicit tap onset markers",
                        "Actuator realization still limited by open-loop stepper behavior",
                    ],
                ),
                card(
                    6.7,
                    1.15,
                    2.8,
                    2.45,
                    title="Next steps",
                    stripe=BLUE,
                    fill="1B2A4A",
                    title_color="FFFFFF",
                    body_color="F6F8FA",
                    bullets_list=[
                        "Run repeated trials per controller",
                        "Make disturbance timing measurable",
                        "Explore more actuator-aware nonlinear control",
                    ],
                ),
                text(
                    0.55,
                    4.25,
                    8.8,
                    0.42,
                    "Most importantly, the thesis shows how much practical control rigor lives between the equations and the motor driver.",
                    size=13,
                    color="FFFFFF",
                    bold=True,
                    align="center",
                ),
            ],
        ),
    ]

    return {
        "meta": {
            "title": "Rotary Inverted Pendulum Thesis Deck",
            "deck_filename": "rotary_inverted_pendulum_thesis_deck.pptx",
            "base_deck_filename": "rotary_inverted_pendulum_thesis_base.pptx",
            "manifest_filename": "build_manifest.json",
        },
        "slides": slides,
    }
